notifications:
  email: false

# Quick boot options
sudo: false
cache: yarn

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: TUQNWpARHa3/7dVcGMxZncCFYJ+a6DzRFCkjDoY3u671YuxXrcOkHFc8yCgX7AUoL0pQuWUaCzmct6AiESmSelQq9X41TOD5RZkROxNhrrrveW5vVa/ncnc2b56Qdz6QnKqW+KJxXoJlt5ePxWd1wsfVAnOJM4GgQy/QTT51766Xov2PzlHwrXe44G1QVUfL5nGcMZbV6BMwWFOdSctzIkePMJI6eTGkPnn8aKVJ5A8KAR250ZRXxo8cpVvhCLfS64rnyBFWHlpm6JGh47IqAx2VanR6px5rW624LafkyGJ0C17FeZ1Ea4C92NfOrY6sb4HFsnFw4/d7+aGKMfuUh93hFZBIDL26Uf54ZA9yMyI8dyOou0kBig/Dfk5nQw7FkVOXjrbqfwI/xRaXVTX96eMkvyV5CBgOZkpBg5pLma4+Lw5HiIVbfzsDBjZitcU4EN7cG0w7rPnKmGQgsr9BOsF2CJ7y4cQyru/04D7F+8irtgeu/Rvf+H9ZKncOukfxqluptVcJGh+A9eUJVhoIxjyqfznbRHOFz7GY1Zxm3w0HBwY9N8hWMR2XpiNqHrDlm+UeMJau6nM4DUHRThby5XJ7c/i0uDcBQpR4csifSfCWXkehAWD8PuFuy0x6P62wfsxaVHfHPXEekmOhfVabHD5L4QHNqEb0j1bq69f2+rk=

# Language options
language: node_js
node_js:
  - 10
script:
  - yarn cover
  - yarn lint

# Npm publish options
before_deploy:
  - yarn build
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: m8q4CZv3jG7Bc6IZPKsHLzKtYghocgjriO/2cJYGeDZR0/iDUaDcjvgdjMn1s4l+3RjWONI3GMTl4M7L6IX2wpeMijIfajTMVnXneIHUfQswzjxBmMfbcItMD67n2ky5szZD7SGdWfqMMXqquHeg9WrBTe6u5eyuFcS+55cPlDB/ut/73rLHlJy/8JSu1B42a3hHd7a+fE41fTyYYErjiL45VjTRCGu1HLlbLieqJOq9AExepqo0MZcXrKUoy1P2aflhqfT+MOBR1IYGJV9ErK/qqTTXUnzLC8wn8O4356FVsu5m42ChPW1/geY9paS1mmsqSRdjwORDZNIrsw+47BMPuPLnIlsCaYtIt0uv+N5FWr2jLBGnCgF+LDTe7qQ/pmn7Xc5eqKyuq9J80m0zUKJZi2YRN118avPNHnjngrzjfz0VybkpMHuj4HOXHUrpd6VPZH/O1aHey/1hXcKbwRh/rR8vevAWZfGy3yz7tqUBQR+/Js0LIjXhh3mSPHrt90lwSjNZ6FYu7Nwyi7IRC8zdY6G4QA0CV1ZBweHzQ/Uo3se5uuCV4vvUvql39jT+XfFVdt+c6oox6DUZo8Gne2g+Wsb21ydbEPu9XcD7sqKDleuRRNLL3SMz221qX6IrOOQV+1V/18ecnvu9+35hx67lInNlm7aEDlp1cgClf7I=
  on:
    node: 10
